<?php
return array (
  'site_title' => 'Mall',
  'time_zone' => '8',
  'time_format_simple' => 'Y-m-d',
  'time_format_complete' => 'Y-m-d H:i:s',
  'price_format' => '¥%s',
  'default_goods_image' => 'data/system/default_goods_image.jpg',
  'default_store_logo' => 'data/system/default_store_logo.jpg',
  'default_user_portrait' => 'data/system/default_user_portrait.jpeg',
  'statistics_code' => 'xdfaaa',
  'guest_comment' => '0',
  'rewrite_enabled' => '1',
  'sitemap_enabled' => '0',
  'sitemap_frequency' => '1',
  'session_type' => 'mysqli',
  'cache_server' => 'memcache',
  'enable_radar' => '0',
  'site_name' => 'tpMall',
  'site_description' => 'default_site_description',
  'site_keywords' => 'ecmall mall',
  'site_logo' => 'data/system/site_logo.jpeg',
  'icp_number' => '',
  'site_status' => '1',
  'closed_reason' => '',
  'hot_search' => '外套,女装,女鞋,女裙,女裤',
  'captcha_status' => 
  array (
    'register' => '1',
    'goodsqa' => '1',
  ),
  'store_allow' => '1',
  'enabled_subdomain' => '0',
  'subdomain_suffix' => '',
  'subdomain_reserved' => 'www',
  'subdomain_length' => '3-12',
);
